### ISSUE TITLE
Add support for LocalDate

### ISSUE THREAD

**Issue by Saberos** [joel-costigliola/assertj-joda-time#17]
As per the comment at http://joel-costigliola.github.io/assertj/assertj-joda-time.html, I'd like to request support for LocalDates to be added.

I just migrated some code to use a LocalDate instead of a DateTime since the time aspect was not actually needed and was simply causing issues. While migrating some tests I was surprised to find out only LocalDateTime and DateTime were supported, not LocalDate (or others such as DateMidnight and LocalTime).

**Comment by joel-costigliola** [comment]
That is a missing piece indeed.

Want to contribute it ?
