### ISSUE TITLE
assertThat(DateTime).isEqualTo() should gracefully handle nulls

### ISSUE THREAD

**Issue by adammichalik** [joel-costigliola/assertj-joda-time#8]
AssertJ-Joda-Time 1.1.0

```java
    @Test
    public void assertActualNull() {
        Assertions.assertThat((DateTime) null).isEqualTo("...");
    }
```
fails with an NPE
```java
java.lang.NullPointerException
	at org.assertj.jodatime.api.DateTimeAssert.isEqualTo(DateTimeAssert.java:474)
```
Would be much nicer to have a more descriptive failure, eg. `Expecting actual not to be null` or `Expected: "..." Actual: null`

**Comment by joel-costigliola** [comment]
I agree.
Thanks for reporting this.

**Comment by SwamWithTurtles** [comment]
I've opened a pull request for this here: 

https://github.com/joel-costigliola/assertj-joda-time/pull/14

**Comment by joel-costigliola** [comment]
Fixed.
